// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/about.tsx";
import * as $1 from "./routes/add.tsx";
import * as $2 from "./routes/api/joke.ts";
import * as $3 from "./routes/api/random-uuid.ts";
import * as $4 from "./routes/canvas.tsx";
import * as $5 from "./routes/countdown.tsx";
import * as $6 from "./routes/gen-omino.tsx";
import * as $7 from "./routes/github/[username].tsx";
import * as $8 from "./routes/greet/[name].tsx";
import * as $9 from "./routes/index.tsx";
import * as $10 from "./routes/search.tsx";
import * as $$0 from "./islands/Add.tsx";
import * as $$1 from "./islands/Canvas.tsx";
import * as $$2 from "./islands/Countdown.tsx";
import * as $$3 from "./islands/Counter.tsx";
import * as $$4 from "./islands/GenOmino.tsx";

const manifest = {
  routes: {
    "./routes/about.tsx": $0,
    "./routes/add.tsx": $1,
    "./routes/api/joke.ts": $2,
    "./routes/api/random-uuid.ts": $3,
    "./routes/canvas.tsx": $4,
    "./routes/countdown.tsx": $5,
    "./routes/gen-omino.tsx": $6,
    "./routes/github/[username].tsx": $7,
    "./routes/greet/[name].tsx": $8,
    "./routes/index.tsx": $9,
    "./routes/search.tsx": $10,
  },
  islands: {
    "./islands/Add.tsx": $$0,
    "./islands/Canvas.tsx": $$1,
    "./islands/Countdown.tsx": $$2,
    "./islands/Counter.tsx": $$3,
    "./islands/GenOmino.tsx": $$4,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
